-- 0003_seed_business_types.sql
-- Starter packs for each kind of wedding business: services with typical prices,
-- sales stages, an event checklist and KRAs. Owners can change all of it.
-- Generated once from a readable list; edit by adding a new migration, not this file.

INSERT INTO business_types (id, name, description, icon, sort_order, starter_pack) VALUES
  ('makeup_artist', 'Makeup artist', 'Bridal, party and family makeup, hair styling', 'sparkles', 10,
   '{"services":[{"name":"Bridal HD makeup","unit":"event","price":25000},{"name":"Airbrush bridal makeup","unit":"event","price":35000},{"name":"Engagement / reception makeup","unit":"event","price":15000},{"name":"Family & guest makeup","unit":"person","price":3500},{"name":"Hair styling","unit":"person","price":2500},{"name":"Saree / dupatta draping","unit":"person","price":1000}],"pipelineStages":["New enquiry","Contacted","Trial booked","Quote sent","Booked","Lost"],"checklist":[{"title":"Trial session done","when":"before"},{"title":"Look and products finalised with bride","when":"before"},{"title":"Kit packed and checked","when":"before"},{"title":"Reach venue on time","when":"on_day"},{"title":"Touch-up kit handed over","when":"on_day"},{"title":"Photos collected for portfolio","when":"after"},{"title":"Review requested","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"staff","title":"Clients ready on time"}]}'::jsonb),
  ('mehendi_artist', 'Mehendi artist', 'Bridal and guest mehendi', 'hand', 20,
   '{"services":[{"name":"Bridal mehendi (full hands & feet)","unit":"event","price":15000},{"name":"Guest mehendi","unit":"person","price":500},{"name":"Groom mehendi","unit":"event","price":2500},{"name":"Artist per hour","unit":"hour","price":1500}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Design finalised with bride","when":"before"},{"title":"Cones prepared and tested","when":"before"},{"title":"Artists assigned","when":"before"},{"title":"Arrive and set up","when":"on_day"},{"title":"Aftercare shared with bride","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb),
  ('wedding_planner', 'Wedding planner', 'Full planning, coordination and vendor management', 'clipboard-list', 30,
   '{"services":[{"name":"Full wedding planning","unit":"event","price":500000},{"name":"Day-of coordination","unit":"day","price":75000},{"name":"Destination wedding management","unit":"event","price":1000000},{"name":"Vendor sourcing only","unit":"event","price":100000},{"name":"Guest hospitality desk","unit":"day","price":40000}],"pipelineStages":["New enquiry","Contacted","Meeting done","Proposal sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Budget and guest count agreed","when":"before"},{"title":"Venue locked","when":"before"},{"title":"All vendors booked","when":"before"},{"title":"Run sheet shared with vendors","when":"before"},{"title":"Guest travel and rooms confirmed","when":"before"},{"title":"On-ground team briefed","when":"on_day"},{"title":"Vendor payments settled","when":"after"},{"title":"Client feedback taken","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"manager","title":"Vendors confirmed on schedule"}]}'::jsonb),
  ('decorator', 'Wedding decorator', 'Mandap, stage, floral and venue decor', 'flower-2', 40,
   '{"services":[{"name":"Mandap decor","unit":"event","price":150000},{"name":"Stage decor","unit":"event","price":100000},{"name":"Entrance and pathway","unit":"event","price":50000},{"name":"Floral centrepieces","unit":"piece","price":2500},{"name":"Haldi / mehendi setup","unit":"event","price":60000}],"pipelineStages":["New enquiry","Contacted","Site visit done","Design sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Site visit and measurements","when":"before"},{"title":"Design approved by client","when":"before"},{"title":"Material and flowers ordered","when":"before"},{"title":"Labour and transport booked","when":"before"},{"title":"Setup complete before guests","when":"on_day"},{"title":"Dismantle and material returned","when":"after"},{"title":"Photos for portfolio","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"staff","title":"Setup finished before deadline"}]}'::jsonb),
  ('event_decorator', 'Birthday & event decorator', 'Birthdays, baby showers, anniversaries and small events', 'party-popper', 50,
   '{"services":[{"name":"Balloon decor package","unit":"event","price":8000},{"name":"Theme birthday setup","unit":"event","price":20000},{"name":"Backdrop and props","unit":"event","price":6000},{"name":"Table decor","unit":"piece","price":800}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Theme and colours confirmed","when":"before"},{"title":"Material packed","when":"before"},{"title":"Setup done 1 hour before","when":"on_day"},{"title":"Material collected","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb),
  ('photographer', 'Photographer & filmmaker', 'Wedding photography, films, pre-wedding shoots', 'camera', 60,
   '{"services":[{"name":"Wedding photography","unit":"day","price":60000},{"name":"Cinematic wedding film","unit":"event","price":150000},{"name":"Pre-wedding shoot","unit":"event","price":50000},{"name":"Candid photographer","unit":"day","price":35000},{"name":"Photo album (40 pages)","unit":"piece","price":20000},{"name":"Drone coverage","unit":"day","price":15000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Shot list agreed with couple","when":"before"},{"title":"Team and gear assigned","when":"before"},{"title":"Batteries and cards ready","when":"before"},{"title":"All functions covered","when":"on_day"},{"title":"Data backed up twice","when":"after"},{"title":"Sneak peek delivered","when":"after"},{"title":"Final photos and film delivered","when":"after"},{"title":"Album designed and approved","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"staff","title":"Deliverables sent on time"}]}'::jsonb),
  ('content_creator', 'Wedding content creator', 'Same-day reels, social media coverage', 'clapperboard', 70,
   '{"services":[{"name":"Same-day reels package","unit":"event","price":30000},{"name":"Full wedding content coverage","unit":"day","price":25000},{"name":"Behind-the-scenes stories","unit":"day","price":10000},{"name":"Extra reel","unit":"piece","price":4000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Content plan and trending audio chosen","when":"before"},{"title":"Couple''s handles noted","when":"before"},{"title":"Reels delivered same day","when":"on_day"},{"title":"Raw clips handed over","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb),
  ('sound_lighting', 'Sound, lighting & DJ', 'DJ, sound systems, lighting and LED walls', 'speaker', 80,
   '{"services":[{"name":"DJ with sound (up to 300 guests)","unit":"event","price":40000},{"name":"Line array sound system","unit":"event","price":75000},{"name":"Stage and venue lighting","unit":"event","price":50000},{"name":"LED wall","unit":"day","price":45000},{"name":"Generator backup","unit":"day","price":15000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Venue power checked","when":"before"},{"title":"Song list and cues from family","when":"before"},{"title":"Equipment tested and loaded","when":"before"},{"title":"Sound check done","when":"on_day"},{"title":"Equipment packed and counted","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"staff","title":"Equipment returned without damage"}]}'::jsonb),
  ('bar_services', 'Bar & beverage services', 'Bartenders, mocktails, cocktail bars', 'wine', 90,
   '{"services":[{"name":"Bartender","unit":"person","price":4000},{"name":"Mocktail counter","unit":"plate","price":250},{"name":"Cocktail bar setup","unit":"event","price":30000},{"name":"Glassware and bar setup","unit":"event","price":15000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Licence and permissions checked","when":"before"},{"title":"Menu approved","when":"before"},{"title":"Stock and ice arranged","when":"before"},{"title":"Bar open on time","when":"on_day"},{"title":"Stock reconciled","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb),
  ('caterer', 'Caterer', 'Wedding and event catering', 'utensils', 100,
   '{"services":[{"name":"Veg buffet","unit":"plate","price":900},{"name":"Non-veg buffet","unit":"plate","price":1200},{"name":"Live counters","unit":"event","price":25000},{"name":"Breakfast / hi-tea","unit":"plate","price":350},{"name":"Service staff","unit":"person","price":1200}],"pipelineStages":["New enquiry","Contacted","Tasting done","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Menu finalised","when":"before"},{"title":"Final guest count confirmed","when":"before"},{"title":"Groceries and staff arranged","when":"before"},{"title":"Food ready on time","when":"on_day"},{"title":"Leftovers and utensils handled","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"manager","title":"Food served on time"}]}'::jsonb),
  ('gifting', 'Gifting & hampers', 'Wedding favours, trousseau packing, hampers', 'gift', 110,
   '{"services":[{"name":"Guest favour","unit":"piece","price":400},{"name":"Premium hamper","unit":"piece","price":2500},{"name":"Trousseau packing","unit":"set","price":1500},{"name":"Custom packaging","unit":"piece","price":150}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Sample approved","when":"before"},{"title":"Quantity and names confirmed","when":"before"},{"title":"Material ordered","when":"before"},{"title":"Packing complete","when":"before"},{"title":"Delivered and counted","when":"on_day"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb),
  ('choreographer', 'Choreographer', 'Sangeet choreography and dance classes', 'music', 120,
   '{"services":[{"name":"Sangeet choreography package","unit":"event","price":60000},{"name":"Couple dance","unit":"event","price":20000},{"name":"Family dance (per song)","unit":"piece","price":8000},{"name":"Practice session","unit":"hour","price":2000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Songs and performers listed","when":"before"},{"title":"Practice schedule shared","when":"before"},{"title":"Final rehearsal done","when":"before"},{"title":"Cue sheet given to DJ","when":"on_day"},{"title":"Performance videos collected","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb),
  ('fireworks', 'Fireworks & special effects', 'Fireworks, cold pyros, entry effects', 'flame', 130,
   '{"services":[{"name":"Cold pyro (per piece)","unit":"piece","price":2000},{"name":"Couple entry effects","unit":"event","price":15000},{"name":"Fireworks show","unit":"event","price":50000},{"name":"Smoke / CO2 effects","unit":"event","price":12000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Venue permission and safety checked","when":"before"},{"title":"Material stock confirmed","when":"before"},{"title":"Safety team assigned","when":"on_day"},{"title":"Site cleaned","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"},{"role":"staff","title":"Zero safety incidents"}]}'::jsonb),
  ('other', 'Other wedding business', 'Anything else in weddings and events', 'briefcase', 140,
   '{"services":[{"name":"Standard package","unit":"event","price":25000},{"name":"Per day service","unit":"day","price":10000}],"pipelineStages":["New enquiry","Contacted","Quote sent","Negotiation","Booked","Lost"],"checklist":[{"title":"Requirements confirmed with client","when":"before"},{"title":"Team assigned","when":"before"},{"title":"Delivered on the day","when":"on_day"},{"title":"Payment collected","when":"after"}],"kras":[{"role":"owner","title":"Enquiries converted to bookings"},{"role":"owner","title":"Money collected before the event"},{"role":"manager","title":"Events delivered on time"},{"role":"staff","title":"Tasks completed on time"}]}'::jsonb)
ON CONFLICT (id) DO NOTHING;
