// Writes dist/theme.css: a Tailwind v4 @theme block generated from src/index.ts,
// so the web app's utility classes always match the shared tokens.
import { writeFileSync } from "node:fs";
import { colors, fontSize, radius } from "../dist/index.js";

const lines = [
  "/* Generated by packages/design-tokens/scripts/build-css.mjs. Do not edit. */",
  "@theme {",
  "  /* Drop Tailwind's default palette: only the shared tokens exist as colours. */",
  "  --color-*: initial;",
];
for (const [name, value] of Object.entries(colors)) lines.push(`  --color-${name}: ${value};`);
for (const [name, value] of Object.entries(radius)) lines.push(`  --radius-${name}: ${value}px;`);
for (const [name, [size, lineHeight]] of Object.entries(fontSize)) {
  lines.push(`  --text-${name}: ${size / 16}rem;`);
  lines.push(`  --text-${name}--line-height: ${lineHeight / 16}rem;`);
}
lines.push("}", "");

writeFileSync(new URL("../dist/theme.css", import.meta.url), lines.join("\n"));
console.log("design-tokens: wrote dist/theme.css");
