// Writes dist/theme.css: a Tailwind v4 theme generated from src/index.ts, so the web
// app's utility classes always match the shared tokens.
import { writeFileSync } from "node:fs";
import { colors, fontSize, gradients, heroGlow, radius, shadows, sun } from "../dist/index.js";

const linear = ({ angle, stops }) => `linear-gradient(${angle}deg, ${stops.join(", ")})`;
const g = heroGlow.sun;
const hero = [
  `radial-gradient(${g.width}px ${g.height}px at ${g.x} ${g.y}, ${g.stops[0]} 0%, ${g.stops[1]} 20%, ${g.stops[2]} 36%, rgba(255, 247, 236, 0) 66%)`,
  `radial-gradient(700px 500px at 100% 30%, rgba(255, 138, 43, 0.3), transparent 60%)`,
  `linear-gradient(180deg, ${heroGlow.base[0]} 0%, ${heroGlow.base[1]} 58%)`,
].join(",\n    ");

const lines = [
  "/* Generated by packages/design-tokens/scripts/build-css.mjs. Do not edit. */",
  "@theme {",
  "  /* Drop Tailwind's default palette: only the shared tokens exist as colours. */",
  "  --color-*: initial;",
  "  --color-white: #FFFFFF;",
];
for (const [name, value] of Object.entries(colors)) lines.push(`  --color-${name}: ${value};`);
for (const [step, value] of Object.entries(sun)) lines.push(`  --color-sun-${step}: ${value};`);
for (const [name, value] of Object.entries(radius)) lines.push(`  --radius-${name}: ${value}px;`);
for (const [name, [size, lineHeight]] of Object.entries(fontSize)) {
  lines.push(`  --text-${name}: ${size / 16}rem;`);
  lines.push(`  --text-${name}--line-height: ${lineHeight / 16}rem;`);
}
for (const [name, value] of Object.entries(shadows)) lines.push(`  --shadow-${name}: ${value};`);
lines.push(
  "  --animate-rise: rise-in 0.7s cubic-bezier(0.2, 0.7, 0.2, 1) both;",
  "  --animate-pulse-dot: pulse-dot 1.8s ease-out infinite;",
  "  @keyframes rise-in {",
  "    from { opacity: 0; transform: translateY(14px); }",
  "    to { opacity: 1; transform: translateY(0); }",
  "  }",
  "  @keyframes pulse-dot {",
  "    0%, 100% { box-shadow: 0 0 0 0 rgba(33, 195, 107, 0.5); }",
  "    50% { box-shadow: 0 0 0 8px rgba(33, 195, 107, 0); }",
  "  }",
  "}",
  "",
  "/* The saffron-to-gold gradient: logo, main button, active menu item, icon tiles, progress. */",
  "@utility bg-gradient-primary {",
  `  background-image: ${linear(gradients.primary)};`,
  "}",
  "",
  "/* Gradient words in a heading. */",
  "@utility text-gradient {",
  `  background-image: ${linear(gradients.text)};`,
  "  -webkit-background-clip: text;",
  "  background-clip: text;",
  "  color: transparent;",
  "}",
  "",
  "/* Golden-hour glow, only for sign-in style pages. */",
  "@utility bg-hero {",
  `  background: ${hero};`,
  "}",
  "",
);

writeFileSync(new URL("../dist/theme.css", import.meta.url), lines.join("\n"));
console.log("design-tokens: wrote dist/theme.css");
